# Generated by Django 2.2.10 on 2020-04-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profifeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfiFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
